### ISSUE TITLE
not populating tasks from Radicale server calendars

### ISSUE THREAD

**Issue by 11redgears** [intri-in/manage-my-damn-life-nextjs#11]
Setup Steps:

1. I have successfully installed mmdl following the install docs and connected to a mysql database.
2. The /install/ url indicated good database settings, and the install button was successful and populated the database with new tables. 
3. It took me to a new user page, and creating a user was successful. 
4. Next I added my CalDAV server (Radicale v3). This authorized successfully and pulled in my 2 calendars. Looking at the sql database, the urls to the calendars are correct.

However, I do not see any tasks.

When I click the refresh button, the console reports:

```
=====================
[]
=====================
```

I am able to create a new task in either of the calendars, and see it in both the mmdl interface as well as my Radicale calDAV server. This new task also appears in the mobile calDAV client I use, Tasks.org.
```
=====================
/api/caldav/calendars/add/event
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Manage my Damn Life Tasks v0.1
BEGIN:VTODO
UID: 49dc56103f5f1d6a828ec4be1d17771e1041d53d30b0cce6ad8f70c7c2c4ef85
DTSTAMP:20230428T140804
SUMMARY:test
STATUS:NEEDS-ACTION
PERCENT-COMPLETE:0
PRIORITY:1
DESCRIPTION: Sdfd
LAST-MODIFIED:20230428T140804
END:VTODO
END:VCALENDAR
=====================
```

It appears pushing tasks to the server works fine, but it cannot find the existing tasks.

Thanks a lot, I am enjoying this tool

**Comment by intri-in** [comment]
Hi, thanks for taking the time to test the client.

I looked into the problem, and I have fixed it. The commit has been merged with "main".


If you find time, do try the fix and let me know if it works.

**Comment by 11redgears** [comment]
This change fixed the issue for me. Thank you for your work, using this daily now.

**Comment by JPDVM2014** [comment]
Sorry to resurrect a closed issue, but what url did you use to get Radicale to work? I've tried everything I can think of with no luck.

**Comment by intri-in** [comment]
Are you using MMDL with docker? 

Is radicale hosted locally?

**Comment by JPDVM2014** [comment]
Yes. Using docker for both MMDL and radicale. Both hosted locally. I've tried using the external and internal URLs for radicale.

**Comment by intri-in** [comment]
I am not familiar with docker image for Radicale. I think it isn't offered by the project itself, but I see a lot of other sources for docker image. Could you tell me which one you're using? I will investigate. It would also be useful if you could tell me how you started the docker  container of radicale.

> the external and internal URLs for radicale.

Could you please elaborate a little more?
 
I am guessing you can access your radicale from your host? 

Could you tell me the command you used to start docker container for MMDL? 

You can try to start MMDL docker with ``` --add-host host.docker.internal:host-gateway ``` option. Then you will be able to use ```host.docker.internal`` as your address for your radicale.

**Comment by boolGhosts** [comment]
I have both radicale and MMDL installed natively without Docker. In my case I use http://<hostname>:<port>/<username> in MMDL, or other caldav clients.

I also have it externally hosted through cloudflare tunnels. In this case, it's https://<domain>/<username>.

**Comment by JPDVM2014** [comment]
> I am not familiar with docker image for Radicale. I think it isn't offered by the project itself, but I see a lot of other sources for docker image. Could you tell me which one you're using? I will investigate. It would also be useful if you could tell me how you started the docker  container of radicale.
> 
> > the external and internal URLs for radicale.
> 
> Could you please elaborate a little more?
>  
> I am guessing you can access your radicale from your host? 
> 
> Could you tell me the command you used to start docker container for MMDL? 
> 
> You can try to start MMDL docker with ``` --add-host host.docker.internal:host-gateway ``` option. Then you will be able to use ```host.docker.internal`` as your address for your radicale.

I use radicale with davx5. I tried my internal IP "192.168....", and I also have radicale through a reverse proxy, so I tried that too.

I used the docker compose intructions to start up mmdl. Everything seems to work fine other than connecting to a caldav service.

I also started a Baikal container, with no luck. Both services give me incorrect credential errors, even though the username and passwords are correct.

I can see in the radicale logs that MMDL attempts to connect, but radicale throws a "Access to the requested resource forbidden." error. 

It may be a combination of radicale problems too, but Baikal does the same thing.

**Comment by intri-in** [comment]
> http://<hostname>:<port>/<username> in MMDL, or other caldav clients.

For the simplest cases, the Caldav address for baikal is:

```http://your-ip-or-address/dav.php```

and for radicale is simply:

```http://your-ip-or-address:5232/``` or ```http://your-ip-or-address:5232/.web/```


> EDIT: Forgot the radicale docker image. It is https://hub.docker.com/r/tomsquest/docker-radicale/

This is the same docker image I tried, and it seems to work.

Let me investigate this, and see if I can reproduce the access denied error.

**Comment by JPDVM2014** [comment]
> > http://<hostname>:<port>/<username> in MMDL, or other caldav clients.
> 
> For the simplest cases, the Caldav address for baikal is:
> 
> ```http://your-ip-or-address/dav.php```
> 
> and for radicale is simply:
> 
> ```http://your-ip-or-address:5232/``` or ```http://your-ip-or-address:5232/.web/```
> 
> 
> > EDIT: Forgot the radicale docker image. It is https://hub.docker.com/r/tomsquest/docker-radicale/
> 
> This is the same docker image I tried, and it seems to work.
> 
> Let me investigate this, and see if I can reproduce the access denied error. 
> 

I fixed one issue with radicale. MMDL wasn't playing nice with a special character in my password. Changed to alphanumeric only, amd it seems to work. But now I have a different issue. i'll open a new issue here. Thanks!
