### ISSUE TITLE
Possibility to move event to anothet calendar

### ISSUE THREAD

**Issue by Knud3** [intri-in/manage-my-damn-life-nextjs#132]
Now calendar selection is grayed out in `Edit Event` view and should give option to choose different calendar.

**Comment by Knud3** [comment]
Calendar selection is still grayed out even there is `Copy/Move to Calendar` text.

**Comment by intri-in** [comment]
You can click on the Copy/Move to Calendar option, and it will open a dialog box with options to either copy or move the event to another calendar.

**Comment by Knud3** [comment]
For me it just closes `Edit Event` view.

**Comment by intri-in** [comment]
No dialog box opens for you?

Can you please tell me if it happens on mobile or desktop view. Also what browser you're using.

**Comment by Knud3** [comment]
No dialog box. I'm now on desktop with Firefox.
