### ISSUE TITLE
Incorrect field input placeholder value in add caldav account page

### ISSUE THREAD

**Issue by 11redgears** [intri-in/manage-my-damn-life-nextjs#17]
Noticed this thought I would pass it along.

CalDAV Username and CalDAV Password inputs

![Screenshot 2023-05-09 081627](https://github.com/intri-in/manage-my-damn-life-nextjs/assets/55422972/923d8528-8df8-4d98-8d96-6feb7eb9e780)

**Comment by intri-in** [comment]
Thanks for pointing this out. I've patched it!
