### ISSUE TITLE
Can't create user account

### ISSUE THREAD

**Issue by CarlSinclair** [intri-in/manage-my-damn-life-nextjs#172]
I've been breaking my head on this for hours.

https://domain/install briefly shows the UI for a few seconds before saying "already installed" and blocking everything behind a login dialog. No sign up button or any way of seemingly creating an account.

I'm currently attempting to create the first user through the database but I have no idea how to configure most of these fields so I would appreciate some guidance.

**Comment by CarlSinclair** [comment]
Ah. I realize my error now. I misunderstood the docs. I thought the default behavior did not permit additional users so I had changed it to true.

However changing it back to false hasn't made a registration button appear. I killed the nohup npm run I had started and started another, thinking that would apply the changes but nope. I'm not running docker.

**Comment by intri-in** [comment]
You would have to rebuild the project again. Since you are changing a public variable, NextJS requires the project to be rebuilt again.

```npm run build```

and then  start it again.

**Comment by CarlSinclair** [comment]
Yup that did it. Might wanna mention in the docs though that this shouldn't be done before creating a user or you'd get locked out. Or ideally make it so that the login dialog doesn't lock you out till after you've created a user.

Anyway just my two cents. Thanks for the help, and for the wonderful project. CalDAV is truly a dying breed nowadays.

**Comment by intri-in** [comment]
> ideally make it so that the login dialog doesn't lock you out till after you've created a user.

Yes, this I think would be a good option. Will implement this in the coming releases.

I will close this issue for now. If you face other issues, feel free to open a new one.
