### ISSUE TITLE
Feature Request: sync to google calendar and/or backup in google drive

### ISSUE THREAD

**Issue by DevLenn** [intri-in/manage-my-damn-life-nextjs#174]
![ezgif-4-89e6a4bbbd](https://github.com/user-attachments/assets/3ecb33fb-e8eb-429f-8b33-67e2ff1b038f)

**Comment by intri-in** [comment]
This is definitely on the roadmap, but it will require some rewrites of the core. It might take a while.

**Comment by DevLenn** [comment]
@intri-in nice. keep me up-to-date
