### ISSUE TITLE
Not really and issue

### ISSUE THREAD

**Issue by FriendsAtDawn** [intri-in/manage-my-damn-life-nextjs#91]
I am a newbie. I need some documentation to works.

**Comment by intri-in** [comment]
Hey, do you need documentation for installation? If yes, you can find them [here](https://manage-my-damn-life-nextjs.readthedocs.io/). Docker installation would be the easiest, at least locally.

**Comment by Svetlana-T** [comment]
do you have a demo available?

**Comment by intri-in** [comment]
@Svetlana-T At the moment, no. But I am working on it.
